import type { Metadata } from "next";
import { headers } from "next/headers";
import { ArrowRight } from "lucide-react";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop";
import CookieConsent from "@/components/CookieConsent";
import ChatWidgetLoader from "@/components/ChatWidgetLoader";
import CommandPalette from "@/components/CommandPalette";
import { CurrencyProvider } from "@/lib/currency";

export const metadata: Metadata = {
  title: "Nexus Web Lab — AI Automation & AI-Powered Web Development",
  description: "AI automation, AI chatbots & AI-powered web development in Yangon, Myanmar. Custom AI agents, business automation & SaaS apps — get a free consultation.",
  openGraph: {
    title: "Nexus Web Lab — AI Automation & AI-Powered Web Development",
    description: "AI automation, AI chatbots & AI-powered web development in Yangon, Myanmar. Custom AI agents, business automation & SaaS apps.",
    url: "https://nexusweblab.com",
    siteName: "Nexus Web Lab",
    locale: "en_MM",
    type: "website",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Nexus Web Lab — Web Design & Development Agency in Yangon",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Nexus Web Lab — AI Automation & AI-Powered Web Development",
    description: "AI automation, AI chatbots & AI-powered web development in Yangon, Myanmar. Custom AI agents & SaaS apps.",
    site: "@nexusweblab",
    creator: "@nexusweblab",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Nexus Web Lab — Web Design & Development Agency in Yangon",
      },
    ],
  },
  metadataBase: new URL("https://nexusweblab.com"),
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/favicon-64.png", sizes: "64x64", type: "image/png" },
      { url: "/favicon-96.png", sizes: "96x96", type: "image/png" },
      { url: "/favicon-180.png", sizes: "180x180", type: "image/png" },
    ],
    apple: "/apple-icon.png",
  },
  manifest: "/manifest.json",
  robots: {
    index: true,
    follow: true,
  },

};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Nonce generated by middleware.ts — applied to Next's own inline scripts
  // automatically; we attach it to the JSON-LD block so it isn't blocked by CSP.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebSite",
        "@id": "https://nexusweblab.com/#website",
        url: "https://nexusweblab.com",
        name: "Nexus Web Lab",
        description: "AI Automation & AI-Powered Web Development in Yangon, Myanmar.",
        inLanguage: "en",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-web-design",
        serviceType: "Web Design",
        name: "Web Design Services",
        description: "Modern, conversion-focused website design for businesses in Myanmar and worldwide.",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-web-development",
        serviceType: "Web Development",
        name: "Web Development Services",
        description: "Fast, scalable websites and web apps built with Next.js, React, and TypeScript.",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-ecommerce",
        serviceType: "E-Commerce Development",
        name: "E-Commerce Development",
        description: "Online stores with payment gateway integration including KBZPay, AYA Pay, and Wave.",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-ai-automation",
        serviceType: "AI Automation",
        name: "Business Automation Systems",
        description: "AI-powered business automation — workflow automation, lead routing, invoicing, reporting and AI chatbots that work 24/7.",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-ai-agents",
        serviceType: "AI Agent Development",
        name: "Custom AI Agent Solutions",
        description: "Custom AI agents trained on your business data — customer support, sales, scheduling and operations, integrated with your tools.",
      },
    ],
  };
  return (
    <html lang="en">
      <head></head>
      <body className="min-h-screen flex flex-col">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[10000] focus:bg-white focus:text-navy focus:px-4 focus:py-2 focus:rounded-lg focus:shadow-lg focus:text-sm focus:font-semibold"
        >
          Skip to main content
        </a>
        <script type="application/ld+json" nonce={nonce} dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        <CurrencyProvider>
          <ScrollToTop />
          {children}
          {/* Mobile-only sticky CTA bar — audit fix: primary CTA must be reachable
              without scrolling (crawlers + users on small screens). Desktop hero CTA stays. */}
          <div className="md:hidden fixed bottom-0 inset-x-0 z-[9990] bg-[#0F1D45]/95 backdrop-blur border-t border-white/10 px-4 pt-2.5 pb-[calc(env(safe-area-inset-bottom,0px)+0.625rem)]">
            <a href="/get-quote" className="gradient-btn w-full flex items-center justify-center gap-2 text-sm font-bold px-4 min-h-[48px] rounded-xl">
              Start Your Project <ArrowRight size={18} />
            </a>
          </div>
          <ChatWidgetLoader />
          <CommandPalette />
          <CookieConsent />
        </CurrencyProvider>
      </body>
    </html>
  );
}
