import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop";
import CookieConsent from "@/components/CookieConsent";
import { CurrencyProvider } from "@/lib/currency";

// Self-hosted Inter with preload + swap (no render-blocking Google Fonts request,
// no FOIT, no CLS from font fallback)
const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--font-inter" });

// Code-split the chat widget — it's a heavy client component (~378 lines) and
// is not needed for first paint. Dynamic import keeps it out of the main bundle.
const ChatWidget = dynamic(() => import("@/components/ChatWidget"), {
  loading: () => null,
});

export const metadata: Metadata = {
  title: "Nexus Web Lab — Web Design & Development Agency in Yangon",
  description: "Web design & development agency in Yangon, Myanmar. We build fast, modern websites, apps, and e-commerce stores for growing businesses.",
  openGraph: {
    title: "Nexus Web Lab — Web Design & Development Agency in Yangon",
    description: "Web design & development agency in Yangon, Myanmar. We build fast, modern websites, apps, and e-commerce stores for growing businesses.",
    url: "https://nexusweblab.com",
    siteName: "Nexus Web Lab",
    locale: "en_MM",
    type: "website",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Nexus Web Lab — Web Design & Development Agency in Yangon",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Nexus Web Lab — Web Design & Development Agency in Yangon",
    description: "Web design & development agency in Yangon, Myanmar. We build fast, modern websites, apps, and e-commerce stores for growing businesses.",
    site: "@nexusweblab",
    creator: "@nexusweblab",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Nexus Web Lab — Web Design & Development Agency in Yangon",
      },
    ],
  },
  metadataBase: new URL("https://nexusweblab.com"),
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/favicon-64.png", sizes: "64x64", type: "image/png" },
      { url: "/favicon-96.png", sizes: "96x96", type: "image/png" },
      { url: "/favicon-180.png", sizes: "180x180", type: "image/png" },
    ],
    apple: "/apple-icon.png",
  },
  manifest: "/manifest.json",
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "https://nexusweblab.com",
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Nonce generated by middleware.ts — applied to Next's own inline scripts
  // automatically; we attach it to the JSON-LD block so it isn't blocked by CSP.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "LocalBusiness",
        "@id": "https://nexusweblab.com/#business",
        name: "Nexus Web Lab",
        description: "Professional web design and development agency in Yangon, Myanmar. We build fast, modern websites, apps, and e-commerce stores.",
        url: "https://nexusweblab.com",
        email: "info@nexusweblab.com",
        telephone: "+95 9 886 264 582",
        address: {
          "@type": "PostalAddress",
          streetAddress: "No.189, Kha 6 Street, Insein",
          addressLocality: "Yangon",
          addressRegion: "Yangon Region",
          addressCountry: "MM",
        },
        geo: {
          "@type": "GeoCoordinates",
          latitude: 16.8955,
          longitude: 96.1085,
        },
        openingHoursSpecification: [
          {
            "@type": "OpeningHoursSpecification",
            dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            opens: "09:00",
            closes: "18:00",
          },
        ],
        areaServed: "Yangon, Myanmar",
        priceRange: "$200 - $5,000+",
        image: "https://nexusweblab.com/logo.png",
        logo: "https://nexusweblab.com/logo.png",
        sameAs: ["https://www.facebook.com/people/Nexus-Web-Lab/61593132628840"],
      },
      {
        "@type": "WebSite",
        "@id": "https://nexusweblab.com/#website",
        url: "https://nexusweblab.com",
        name: "Nexus Web Lab",
        description: "Web design & development agency in Yangon, Myanmar.",
        publisher: { "@id": "https://nexusweblab.com/#business" },
        inLanguage: "en",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-web-design",
        serviceType: "Web Design",
        name: "Web Design Services",
        provider: { "@id": "https://nexusweblab.com/#business" },
        areaServed: "Yangon, Myanmar",
        description: "Modern, conversion-focused website design for businesses in Myanmar and worldwide.",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-web-development",
        serviceType: "Web Development",
        name: "Web Development Services",
        provider: { "@id": "https://nexusweblab.com/#business" },
        areaServed: "Yangon, Myanmar",
        description: "Fast, scalable websites and web apps built with Next.js, React, and TypeScript.",
      },
      {
        "@type": "Service",
        "@id": "https://nexusweblab.com/#service-ecommerce",
        serviceType: "E-Commerce Development",
        name: "E-Commerce Development",
        provider: { "@id": "https://nexusweblab.com/#business" },
        areaServed: "Yangon, Myanmar",
        description: "Online stores with payment gateway integration including KBZPay, AYA Pay, and Wave.",
      },
    ],
  };
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://images.unsplash.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://images.unsplash.com" />
      </head>
      <body className={`${inter.variable} min-h-screen flex flex-col`}>
        <script type="application/ld+json" nonce={nonce} dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        <CurrencyProvider>
          <ScrollToTop />
          {children}
          <ChatWidget />
          <CookieConsent />
        </CurrencyProvider>
      </body>
    </html>
  );
}
