import type { BlogPost } from "@/lib/blog";

// File-based blog posts — published without DB access. Any DB post with the
// same slug wins, so these act as ready-made content until migrated via /admin.
export const STATIC_POSTS: BlogPost[] = [
  {
    id: "static-seo-myanmar-businesses-guide-2026",
    title: "SEO for Myanmar Businesses: A Beginner's Guide (2026)",
    slug: "seo-myanmar-businesses-guide-2026",
    excerpt: "Most people in Myanmar find a business the same way: they search on Google. If your business does not show up when someone searches for what you sell, you are invisible to your best customers.",
    content: "Most people in Myanmar find a business the same way: they search on Google. If your business does not show up when someone searches for what you sell, you are invisible to your best customers.\n\nSearch engine optimization (SEO) fixes that. This guide explains how SEO works for Myanmar businesses and how to start — without jargon.\n\n## What is SEO?\n\nSEO is the practice of making your website show up higher in Google search results for the words your customers type. Higher ranking means more visitors, more enquiries, and more sales — without paying for every click like you do with ads.\n\n## How Myanmar customers search\n\nMyanmar customers search in two languages:\n\n- English — \"web design company in Yangon\", \"KBZPay payment gateway\"\n- Burmese — \"website ဆောက်နည်း\", \"online shop ဖွင့်နည်း\"\n\nA good SEO strategy covers both. Your website should target the keywords your customers actually use, in the language they use them.\n\n## The three parts of SEO\n\n1. On-page SEO — your page titles, descriptions, headings, and content should match what people search for.\n2. Technical SEO — your site must load fast, work on mobile, and be easy for Google to read (clean structure, sitemap, no broken links).\n3. Local SEO — for a physical business or a Yangon-based agency, showing up in local results and on Google Maps matters.\n\n## Google Business Profile (free and important)\n\nFor any Myanmar business with a location, a Google Business Profile is the fastest win. It puts your business on Google Maps and in local search results for free.\n\nSteps: create your profile, verify your business, add your address, phone, hours, and photos, and ask happy customers for reviews.\n\n## How long does SEO take?\n\nSEO is a long game. You usually see movement in 1–3 months and meaningful results in 6–12 months. Unlike ads, the results compound — a page that ranks well keeps bringing customers without ongoing ad spend.\n\n## A simple starting checklist\n\n1. List the 10–20 keywords your customers search for.\n2. Make sure each page has a unique title and description.\n3. Submit your sitemap to Google Search Console.\n4. Claim your Google Business Profile.\n5. Write useful content that answers real customer questions.\n\n## The bottom line\n\nSEO is the most cost-effective way to grow online in Myanmar — it works while you sleep. You do not need to master it yourself. Start with the basics above, and get help for the technical parts if you need it.\n\nWant to know how your website is doing on Google? Get a free SEO audit and we will show you exactly where you stand and what to fix first.",
    image: "/images/remote/remote-1561070791-2526d30994b5-1920w.webp",
    tags: ["SEO", "Myanmar Business", "Digital Marketing", "Guide"],
    created_at: "2026-09-14 09:00:00",
  },
  {
    id: "static-website-cost-myanmar-2026",
    title: "How Much Does a Website Cost in Myanmar? (2026 Guide)",
    slug: "website-cost-myanmar-2026",
    excerpt: "How much does a website cost in Myanmar? It is the first question every business owner asks — and the honest answer is: it depends on what you need.",
    content: "How much does a website cost in Myanmar? It is the first question every business owner asks — and the honest answer is: it depends on what you need.\n\nA one-page landing page and a full e-commerce store are very different projects. In this guide, we break down the real price ranges, what drives the cost, and how to get the best value for your budget.\n\n## The short answer\n\nIn Myanmar in 2026, a website typically costs anywhere from $150 to $5,000 or more, depending on the type:\n\n- Simple landing page (1 page): $150 – $400\n- Business website (5–10 pages): $400 – $1,200\n- E-commerce store with payments: $800 – $3,000\n- Custom web app or dashboard: $2,000 – $5,000+\n\nThese are typical market ranges. Your exact price depends on the design, the features, and who builds it.\n\n## What drives the price\n\nFive things affect the final cost:\n\n1. Number of pages — a 10-page site takes more design and writing than a 1-page landing page.\n2. Custom design vs template — a template is faster and cheaper; a custom design reflects your brand and converts better.\n3. Features — forms, booking, payment gateways (KBZPay, Wave Pay, AYA Pay), live chat, and dashboards all add development time.\n4. Content — writing good copy and preparing images takes time, but it is what sells.\n5. Ongoing costs — domain (about $10–15 per year) and hosting ($0–20 per month) are separate from the build.\n\n## Landing page vs full website\n\nA landing page is a single page built to do one thing — usually collect leads or sell one product. It is fast to build and cheap, but it cannot grow with your business.\n\nA full business website has multiple pages (Home, About, Services, Contact) and can rank for many keywords on Google. For most growing businesses, this is the better long-term investment.\n\n## E-commerce: the bigger investment\n\nAn online store needs a product catalog, shopping cart, checkout, and payment integration. In Myanmar, supporting KBZPay and Wave Pay matters because many customers prefer them over cards.\n\nA basic store starts around $800. Adding inventory management, delivery zones, and promotions pushes the price higher — but those features usually pay for themselves in saved time and extra sales.\n\n## How to avoid overpaying\n\n1. Know your goal — if you only need leads, a landing page is enough.\n2. Ask what is included — design, hosting, training, and support should be clear upfront.\n3. Check past work — a real portfolio says more than a low price.\n4. Plan for growth — a slightly larger budget now saves a costly rebuild later.\n\n## The bottom line\n\nA website is not an expense — it is an investment that works for your business 24/7. Start with the smallest thing that achieves your goal, then grow from there.\n\nNot sure what you need? Get a free consultation and we will tell you honestly what fits your budget — no pressure, no jargon.",
    image: "/images/remote/remote-1551288049-bebda4e38f71-1920w.webp",
    tags: ["Web Development", "Pricing", "Myanmar Business", "Guide"],
    created_at: "2026-09-14 09:00:00",
  },
];
